
source "https://rubygems.org"

gem "cucumber", "5.2"
gem "capybara", "3.33"
gem "selenium-webdriver", "3.142"
gem "rspec", "3.10"
gem "faker", "2.15"
gem "mongo", "2.13.1"
gem "allure-cucumber", "2.13.7"
gem "rake"
gem "httparty", "0.18.1"




#como estava 
# source "https://rubygems.org"

# gem "allure-cucumber", "2.13.6.4"
# gem "cucumber", "5.2"
# gem "capybara", "3.33"
# gem "selenium-webdriver", "3.142.7"
# gem "rspec", "3.10"
# gem "faker", "2.14"
# gem "mongo", "2.13.1"
# gem "rake"
# gem "httparty", "0.18.1"



# #projeto api
# gem "rspec", "3.10"
# gem "httparty", "0.18.1"
# gem "mongo", "2.13.1"