require "digest/md5"

require_relative "features/support/libs/mongo"

def to_md5(pass)
    return Digest::MD5.hexdigest(pass)
end


task :test do
    puts "Executando uma tarefa teste"
end

task :local_seeds do 
    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

    users = [
      { name: "Sueli Anuncio", email: "sueli.silvestre@yahoo.com.br", password: to_md5("pwd123") },
      { name: "Sueli Login", email: "sueli.silvestre01@gmail.com", password: to_md5("pwd123") },
      { name: "Anderson Silva", email: "spider01@hotmail.com", password: to_md5("pwd123") },
      { name: "João Anunciante", email: "joao@anunciante.com", password: to_md5("pwd123") },
      { name: "Maria Locataria", email: "maria@locataria.com", password: to_md5("pwd123") },   
    ]

    #Zerando a base e inserindo os usuários da lista, para obter sucesso na execução dos testes
    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)

    sh "cucumber"
end

task :hmg_seeds do 
    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))

    users = [
      { name: "Sueli Anuncio", email: "sueli.silvestre@yahoo.com.br", password: to_md5("pwd123") },
      { name: "Sueli Login", email: "sueli.silvestre01@gmail.com", password: to_md5("pwd123") },
      { name: "Anderson Silva", email: "spider01@hotmail.com", password: to_md5("pwd123") },
      { name: "João Anunciante", email: "joao@anunciante.com", password: to_md5("pwd123") },
      { name: "Maria Locataria", email: "maria@locataria.com", password: to_md5("pwd123") },      
    ]

    #Zerando a base e inserindo os usuários da lista, para obter sucesso na execução dos testes
    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)

    sh "cucumber"
end